"""fixed assoc table and media attrs

Revision ID: d6e98479b964
Revises: f065604cce75
Create Date: 2024-08-06 15:17:33.020076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e98479b964'
down_revision = 'f065604cce75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
